# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newmain.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(814, 600)
        self.mainwidget = QtWidgets.QWidget(MainWindow)
        self.mainwidget.setStyleSheet("QWidget#mainwidget{\n"
"    background-color:white;\n"
"    border-top-left-radius:20px;\n"
"    border-top-right-radius:20px;\n"
"    border-bottom-left-radius:20px;\n"
"    border-bottom-right-radius:20px;\n"
"}")
        self.mainwidget.setObjectName("mainwidget")
        self.menuframe = QtWidgets.QFrame(self.mainwidget)
        self.menuframe.setGeometry(QtCore.QRect(0, 0, 133, 601))
        self.menuframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.menuframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.menuframe.setObjectName("menuframe")
        self.listWidget = QtWidgets.QListWidget(self.menuframe)
        self.listWidget.setGeometry(QtCore.QRect(0, 0, 120, 601))
        self.listWidget.setStyleSheet("QListWidget{\n"
"    background-color:rgb(0, 85, 255);\n"
"    border-top-left-radius:20px;\n"
"    border-top-right-radius:20px;\n"
"    border-bottom-left-radius:20px;\n"
"    border-bottom-right-radius:20px;\n"
"}")
        self.listWidget.setObjectName("listWidget")
        self.verticalScrollBar = QtWidgets.QScrollBar(self.menuframe)
        self.verticalScrollBar.setGeometry(QtCore.QRect(120, 15, 12, 567))
        self.verticalScrollBar.setStyleSheet("QScrollBar:vertical{\n"
"    background-color:white;\n"
"    background-origin:border;\n"
"    border-radius:5px;\n"
"}\n"
"QScrollBar::handle:vertical{\n"
"    background-color:grey;\n"
"    border-radius:6px;\n"
"}")
        self.verticalScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar.setObjectName("verticalScrollBar")
        self.mainframe = QtWidgets.QFrame(self.mainwidget)
        self.mainframe.setGeometry(QtCore.QRect(132, 0, 681, 601))
        self.mainframe.setStyleSheet("QFrame#mainframe{\n"
"    border-top-left-radius:20px;\n"
"    border-top-right-radius:20px;\n"
"    border-bottom-left-radius:20px;\n"
"    border-bottom-right-radius:20px;\n"
"}\n"
"QFrame{\n"
"    background-color:white;\n"
"}")
        self.mainframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mainframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mainframe.setObjectName("mainframe")
        self.verticalScrollBar_2 = QtWidgets.QScrollBar(self.mainframe)
        self.verticalScrollBar_2.setGeometry(QtCore.QRect(669, 15, 12, 567))
        self.verticalScrollBar_2.setStyleSheet("QScrollBar:vertical{\n"
"    background-color:white;\n"
"    background-origin:border;\n"
"    border-radius:5px;\n"
"}\n"
"QScrollBar::handle:vertical {\n"
"    background-color:grey;\n"
"    border-radius:6px;\n"
"}")
        self.verticalScrollBar_2.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar_2.setObjectName("verticalScrollBar_2")
        self.mainwin = QtWidgets.QFrame(self.mainframe)
        self.mainwin.setGeometry(QtCore.QRect(0, 0, 669, 601))
        self.mainwin.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mainwin.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mainwin.setObjectName("mainwin")
        MainWindow.setCentralWidget(self.mainwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Erichat Server"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
